openapi: 3.0.0
info:
  version: 2.0.0
  title: Murmurations Library API
  description: API schema for the Murmurations Library
servers:
  - description: Murmurations Testing Platform
    url: https://test-library.murmurations.network/v1
tags:
  - name: Common Endpoints
paths:
  /ping:
    get:
      tags:
        - Common Endpoints
      summary: Ping the library
      description: |
        Check if the index is live
      responses:
        200:
          description: OK
  /schemas:
    get:
      tags:
        - Common Endpoints
      summary: Get a list of schemas
      description: |
        Indices and Murmurations profile generators (MPGs) will need the list of schemas in the library in order to validate profiles, and MPGs will need them to build input forms and present schemas to users. This endpoint simply returns summary information for all of the schemas available in the library.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GetSchemasResponse'
              example:
                data:
                  - title: 'Test Schema'
                    description: 'Just for testing - Select this schema to see your profile show up straight away on the Test map.'
                    name: 'test_schema-v1'
                    url: 'https://murmurations.network/schemas/test_schema'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    GetSchemasResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              name:
                type: string
              url:
                type: string
            required:
              - title
              - description
              - name
              - url
    Error:
      type: object
      required:
        - message
        - status
      properties:
        message:
          type: string
        status:
          type: integer
  responses:
    TooManyRequests:
      description: The request limit for this resource has been reached for the current rate limit window.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Rate limit exceeded.
            status: 429
    ServerError:
      description: An unknown internal error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Internal server error triggered.
            status: 500
