openapi: 3.0.0
info:
  version: '1.0'
  title: Murmurations Library API
  description: Draft version of the Library API for the Murmurations Protocol
servers:
  - description: Murmurations Testing Platform
    url: https://test-library.murmurations.network/v1
tags:
  - name: Common Endpoints
paths:
  # TODO - future release
  # /fields:
  #   get:
  #     summary: Get a list of fields
  #     description: |
  #       Indices and node UIs will need the list of fields in the library in order to validate profiles, and node UIs will need them to build input forms. This endpoint simply returns all of the fields available in the library.

  #       The examples below do not include a full list of properties that might be returned, but they highlight the main properties to expect in field objects.
  #     responses:
  #       200:
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 data:
  #                   $ref: '#/components/schemas/GetFieldsResponse'
  #             example:
  #               data:
  #                 - name: "mission-v1"
  #                   definition:
  #                     title: "Mission Statement"
  #                     description: "A short statement of why the entity exists, what its overall goal is: what kind of product or service it provides, its primary customers or market, and its geographical region of operation."
  #                     type: "string"
  #                     maxLength: 1000
  #                     context: "https://en.wikipedia.org/wiki/Mission_statement"
  #                 - name: "keywords-v1"
  #                   definition:
  #                     title: "Descriptive Keywords"
  #                     description: "The most common keywords used to describe the entity"
  #                     type: "array"
  #                     items:
  #                         type: "string"
  #                     minItems: 1
  #                     maxItems: 50
  #                     uniqueItems: true
  #                     context: "https://schema.org/keywords"
  #       429:
  #         $ref: '#/components/responses/TooManyRequests'
  #       500:
  #         $ref: '#/components/responses/ServerError'
  /ping:
    get:
      tags:
        - Common Endpoints
      summary: Ping the library
      description: |
        Check if the index is live
      responses:
        200:
          description: OK
  /schemas:
    get:
      tags:
        - Common Endpoints
      summary: Get a list of schemas
      description: |
        Indices and Murmurations profile generators (MPGs) will need the list of schemas in the library in order to validate profiles, and MPGs will need them to build input forms and present schemas to users. This endpoint simply returns summary information for all of the schemas available in the library.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GetSchemasResponse'
              example:
                data:
                  - title: 'Test Schema'
                    description: 'Just for testing - Select this schema to see your profile show up straight away on the Test map.'
                    name: 'test_schema-v1'
                    version: 1
                    url: 'https://murmurations.network/schemas/test_schema'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    # TODO - future release
    # GetFieldsResponse:
    #   type: array
    #   items:
    #     type: object
    #     properties:
    #       name:
    #         type: string
    #       definition:
    #         type: object
    #         properties:
    #           title:
    #             type: string
    #           description:
    #             type: string
    #           type:
    #             type: string
    GetSchemasResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              name:
                type: string
              version:
                type: integer
              url:
                type: string
            required:
              - title
              - description
              - name
              - version
              - url
    Error:
      type: object
      required:
        - message
        - status
      properties:
        message:
          type: string
        status:
          type: integer
  responses:
    TooManyRequests:
      description: The request limit for this resource has been reached for the current rate limit window.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Rate limit exceeded.
            status: 429
    ServerError:
      description: An unknown internal error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Internal server error triggered.
            status: 500
